print("Ingrese el codigo del empleado")
cod = input()
print("Ingrese el primer sueldo del empleado")
x1 = float(input())
print("Ingrese el segundo sueldo del empleado")
x2 = float(input())
print("Ingrese el tercer sueldo del empleado")
x3 = float(input())
print("Ingrese el cuarto sueldo del empleado")
x4 = float(input())
print("Ingrese el quinto sueldo del empleado")
x5 = float(input())
print("Ingrese el sexto sueldo del empleado")
x6 = float(input())
totsem = x1 + x2 + x3 + x4 + x5 + x6
promsem = totsem/6
print("El empleado de codigo " + cod)
print("Recibio un total de ", totsem)
print("Y su promedio es ", promsem)